node_modules/
.glubean/

# Secrets — Glubean loads these into ctx.secrets; never commit them.
.env.secrets
.env.*.secrets

# Local env (vars)
.env
.env.local

# Result files (generated by glubean run / VS Code extension)
*.result.json

*.log
.DS_Store
