/**
 * Smoke test — verifies the DummyJSON API is reachable.
 *
 * This is the only pre-written test. All other test files
 * are generated by YOU (with help from your AI agent).
 *
 * Run: deno task test
 */

import { test } from "@glubean/sdk";

export const apiReachable = test(
  {
    id: "api-reachable",
    name: "DummyJSON API is reachable",
    tags: ["smoke"],
  },
  async (ctx) => {
    const baseUrl = ctx.vars.require("BASE_URL");

    ctx.log("Checking API connectivity...");
    const start = Date.now();

    const res = await fetch(`${baseUrl}/test`);
    const data = await res.json();

    ctx.trace({
      name: "Health check",
      method: "GET",
      url: `${baseUrl}/test`,
      status: res.status,
      duration: Date.now() - start,
      responseBody: data,
    });

    ctx.assert(res.status === 200, "API should return 200", {
      actual: res.status,
      expected: 200,
    });
    ctx.assert(data.status === "ok", "Status should be ok", {
      actual: data.status,
      expected: "ok",
    });

    ctx.log("API is reachable", data);
  }
);
