/**
 * Smoke test — verifies the DummyJSON API is reachable.
 *
 * This is the only pre-written test. All other test files
 * are generated by YOU (with help from your AI agent).
 *
 * Run: deno task test
 */

import { test } from "@glubean/sdk";

export const apiReachable = test(
  {
    id: "api-reachable",
    name: "DummyJSON API is reachable",
    tags: ["smoke"],
  },
  async (ctx) => {
    const baseUrl = ctx.vars.require("BASE_URL");

    ctx.log("Checking API connectivity...");

    const res = await ctx.http.get(`${baseUrl}/test`);

    // Fluent assertion — status must be 200 before parsing body
    ctx.expect(res.status).toBe(200).orFail();

    const data = await res.json();

    // Soft assertions — both run even if the first fails
    ctx.expect(data.status).toBe("ok");
    ctx.expect(data).toHaveProperty("method");

    // Warning — best practice check, does not fail the test
    ctx.warn(
      res.headers.has("content-type"),
      "Response should include content-type header",
    );

    ctx.log("API is reachable", data);
  },
);
